### PR TITLE
Move to all torch nw_cuda implementation

### PR DESCRIPTION
**Pull request by blackwer**
Still uses numba.cuda.jit, but no longer requires device wrappers and CPU transfers! Numba understands torch GPU tensors, so they just work out of the box, so long as the tensor doesn't have "requires_grad" set, which you can temporarily unset for calculations by calling the "detach()" method.

The code should already be multi-gpu capable (if you submit multiple batches to different devices), since everything inherits the device of the input 'theta.' There are no sanity checks (i.e. A.device == theta.device).

### CODE REVIEW

**Comment by mortonjt** [comment]
```
======================================================================
ERROR: test_trainer (__main__.TestTrainer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/juermieboop/miniconda3/envs/pytorch/lib/python3.8/site-packages/numba/core/typing/context.py", line 353, in resolve_argument_type
    return typeof(val, Purpose.argument)
  File "/home/juermieboop/miniconda3/envs/pytorch/lib/python3.8/site-packages/numba/core/typing/typeof.py", line 33, in typeof
    raise ValueError(msg)
ValueError: cannot determine Numba type of <class 'torch.Tensor'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_trainer.py", line 72, in test_trainer
    trainer.fit(model)
  File "/home/juermieboop/miniconda3/envs/pytorch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 979, in fit
    self.single_gpu_train(model)
  File "/home/juermieboop/miniconda3/envs/pytorch/lib/python3.8/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 185, in single_gpu_train
    self.run_pretrain_routine(model)
  File "/home/juermieboop/miniconda3/envs/pytorch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1156, in run_pretrain_routine
    self.train()
  File "/home/juermieboop/miniconda3/envs/pytorch/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 370, in train
    self.run_training_epoch()
  File "/home/juermieboop/miniconda3/envs/pytorch/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 452, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx)
  File "/home/juermieboop/miniconda3/envs/pytorch/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 625, in run_training_batch
    opt_closure_result = self.optimizer_closure(
  File "/home/juermieboop/miniconda3/envs/pytorch/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 772, in optimizer_closure
    training_step_output = self.training_forward(split_batch, batch_idx, opt_idx,
  File "/home/juermieboop/miniconda3/envs/pytorch/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 934, in training_forward
    output = self.model.training_step(*args)
  File "/home/juermieboop/Documents/research/garfunkel/deepblast/trainer.py", line 79, in training_step
    predA = self.aligner(x, y)
  File "/home/juermieboop/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/juermieboop/Documents/research/garfunkel/deepblast/alignment.py", line 77, in forward
    aln = self.nw.decode(theta, A)
  File "/home/juermieboop/Documents/research/garfunkel/deepblast/nw_cuda.py", line 295, in decode
    nll = self.forward(theta, A)
  File "/home/juermieboop/Documents/research/garfunkel/deepblast/nw_cuda.py", line 262, in forward
    return NeedlemanWunschFunction.apply(theta, A, self.operator)
  File "/home/juermieboop/Documents/research/garfunkel/deepblast/nw_cuda.py", line 182, in forward
    _forward_pass_kernel[tpb, bpg](theta.detach(), A, Q, Vt)
  File "/home/juermieboop/miniconda3/envs/pytorch/lib/python3.8/site-packages/numba/cuda/compiler.py", line 833, in __call__
    kernel = self.specialize(*args)
  File "/home/juermieboop/miniconda3/envs/pytorch/lib/python3.8/site-packages/numba/cuda/compiler.py", line 843, in specialize
    [self.typingctx.resolve_argument_type(a) for a in args])
  File "/home/juermieboop/miniconda3/envs/pytorch/lib/python3.8/site-packages/numba/cuda/compiler.py", line 843, in <listcomp>
    [self.typingctx.resolve_argument_type(a) for a in args])
  File "/home/juermieboop/miniconda3/envs/pytorch/lib/python3.8/site-packages/numba/core/typing/context.py", line 355, in resolve_argument_type
    if numba.cuda.is_cuda_array(val):
  File "/home/juermieboop/miniconda3/envs/pytorch/lib/python3.8/site-packages/numba/cuda/api.py", line 75, in is_cuda_array
    return hasattr(obj, '__cuda_array_interface__')
  File "/home/juermieboop/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/tensor.py", line 545, in __cuda_array_interface__
    raise RuntimeError(
RuntimeError: Can't get __cuda_array_interface__ on Variable that requires grad. If gradients aren't required, use var.detach() to get Variable that doesn't require grad.

```

**Comment by mortonjt** [comment]
`conda install hmmer -c bioconda`

**Comment by blackwer** [comment]
OK. I fixed the issue there. The gap score is being passed in with 'requires_grad' set. I detached it for the calculation, but now there is a type error. A is expected to be a rank 1 tensor with B elements, and is being passed in as a rank 2 tensor.

The other issue is, as you mentioned in your PR, the dimensions seem to be getting flipped.

```
        print(len(x[0]), len(y[0]), A.shape, predA.shape)
```
yields `81 74 torch.Size([1, 74, 81]) torch.Size([1, 81, 74])`. This gives rise to `RuntimeError: The size of tensor a (81) must match the size of tensor b (74) at non-singleton dimension 2`.

**Comment by mortonjt** [comment]
This is awesome @blackwer . It looks like I am able to get the GPU code working now with a batch size of 1. 
I'll need to perform some minor tweaks to get it to work with larger batch sizes (should be able to get done before tomorrow). Thanks!

**Comment by mortonjt** [comment]
To make sure that everything is visible, I'm working on another pull request below that begins to hash out larger batch sizes
https://github.com/blackwer/garfunkel/pull/2

**Pull request merged**
